from scanner.rules.base import Rule, Severity, Confidence

RULES: list[Rule] = [
    Rule(
        rule_id="CODE-001",
        title="eval() usage",
        category="dangerous-code",
        severity=Severity.MEDIUM,
        confidence=Confidence.HIGH,
        description="Potential issue detected: use of eval() to evaluate arbitrary input.",
        why_it_matters="eval() executes arbitrary strings as code. If any part of the string is user-controlled, an attacker can run arbitrary commands on the host.",
        recommendation="Remove eval(). Use safer alternatives such as ast.literal_eval() for literal data or a parser tailored to the data format.",
        ai_fix_prompt="Inspect the files that use eval(). Identify where the evaluated string originates and whether it can carry user input. Replace eval() with a safe alternative such as ast.literal_eval() for literal data or a dedicated parser, and restrict input to trusted sources. Modify only the necessary files, avoid unrelated refactoring, and preserve existing behavior. Add or update tests that confirm the replacement behaves identically for legitimate inputs and rejects untrusted ones. Verify the fix, then summarize the changes.",
        technical="eval() compiles and runs its argument in the current scope. Even when the argument looks benign, variable content from request bodies, query strings, or config files can turn it into arbitrary code execution.",
        beginner="eval() runs whatever text you give it as real program code. If a user can change that text, they can make your program do almost anything.",
        patterns=[r"\beval\s*\("],
    ),
    Rule(
        rule_id="CODE-002",
        title="Shell command execution",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: shell or subprocess execution is called.",
        why_it_matters="Shell execution is a prime target for command injection when arguments include user-controlled data, leading to arbitrary command execution on the server.",
        recommendation="Avoid shell invocation. Use subprocess with a list of arguments and shell=False, or use a purpose-built library, and validate inputs with an allowlist.",
        ai_fix_prompt="Inspect the files calling os.system, subprocess, or child_process.exec. Trace where command arguments come from and whether user input can reach them. Replace shell invocation with argument-list form (shell=False) or a safer API, and add validation/allowlisting of inputs. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests covering both safe input and injection attempts. Verify the fix, then summarize the changes.",
        technical="os.system() and subprocess calls with shell=True pass the command string to the platform shell, where metacharacters such as ;, |, and $ are interpreted. Passing a list with shell=False avoids shell interpretation.",
        beginner="These commands let your program talk to the operating system's shell. If a user can slip extra commands into the text, they can run anything on your server.",
        patterns=[
            r"os\.system\s*\(",
            r"subprocess\.(call|run|Popen)\s*\(",
            r"child_process\.exec\s*\(",
            r"child_process\.execSync\s*\(",
            r"execSync\s*\(",
            r"System\.exec\s*\(",
        ],
    ),
    Rule(
        rule_id="CODE-003",
        title="Command injection via interpolated shell call",
        category="dangerous-code",
        severity=Severity.CRITICAL,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: shell execution with interpolated or user-controlled content.",
        why_it_matters="Interpolating variables, format specifiers, or shell metacharacters into a shell command allows command injection, giving an attacker full shell access.",
        recommendation="Never build shell commands from strings containing user input. Prefer argument lists with shell=False and strict allowlist validation of any dynamic component.",
        ai_fix_prompt="Inspect the shell-execution call sites flagged. Identify every interpolated variable or metacharacter and trace its origin. Replace string-built commands with argument-list execution (shell=False) and sanitize or allowlist all dynamic parts. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests with injection payloads to prove they are neutralized. Verify the fix, then summarize the changes.",
        technical="An f-string, format placeholder (such as %s or {}), or $ interpolation inside a shell command merges data directly into shell syntax, so input like `; rm -rf /` becomes part of the executed command line.",
        beginner="Putting a user's text directly into a command line is dangerous. A user can add their own commands with characters like ; or $. Use safe function arguments instead of text.",
        patterns=[
            r"os\.system\s*\(\s*f[\"']",
            r"child_process\.exec\s*\(\s*[\"'][^\"']*(\$|\{)",
            r"exec\s*\(\s*[\"'][^\"']*\$",
        ],
    ),
    Rule(
        rule_id="CODE-004",
        title="SQL query built by string concatenation",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: SQL statement assembled via string concatenation or formatting.",
        why_it_matters="Concatenating or formatting values into SQL enables SQL injection, allowing attackers to read, modify, or delete data they should not access.",
        recommendation="Use parameterized queries or prepared statements everywhere. Never splice variables or request data into SQL text.",
        ai_fix_prompt="Inspect the SQL statements flagged. Locate where user input enters the query string through concatenation, f-strings, or format placeholders. Rewrite them as parameterized queries or prepared statements so data never becomes SQL syntax. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests with SQL injection payloads to confirm they are handled as data. Verify the fix, then summarize the changes.",
        technical="When a query like SELECT * FROM users WHERE id = '{}' is formatted with user input, characters like ' OR 1=1 -- change the query structure. Parameter binding keeps the value as data, never as syntax.",
        beginner="SQL databases follow their own rules of punctuation. If you paste user text into a query, a ' or -- in that text can rewrite what the query does. Parameterized queries keep user text as plain data.",
        patterns=[
            r"(?i)((SELECT|INSERT|UPDATE|DELETE)[^\n]*?)\s*(\+\s|f[\"']|%\(|\$\{)",
        ],
    ),
    Rule(
        rule_id="CODE-005",
        title="Path traversal",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: path construction that can escape the intended directory.",
        why_it_matters="Traversal sequences like ../ combined with user-controlled paths can expose arbitrary files on the server, including credentials and source code.",
        recommendation="Resolve and validate paths against a base directory before use. Reject any path containing .., and never pass raw request parameters to file-serving helpers.",
        ai_fix_prompt="Inspect the flagged path and file-serving code. Identify where request parameters feed into paths or sendFile/join calls. Add canonical path resolution with an allowlist or prefix check so traversal is rejected. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests with ../ payloads to confirm they are blocked. Verify the fix, then summarize the changes.",
        technical="Sequences such as ../ or ..\\ climb the directory tree. Sending user input directly to sendFile or join lets an attacker address files outside the intended root.",
        beginner="../ means 'go up a folder'. A user who controls part of a file path can climb out of the folder you meant to share and read other files. Always check the final path stays inside.",
        patterns=[
            r"(?i)(\.\.\/\.\.\/|\.\.\\|sendFile\s*\(\s*req\.(params|query)|join\s*\(\s*[\"']\.\.)",
        ],
    ),
    Rule(
        rule_id="CODE-006",
        title="Unsafe file upload handling",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: upload or request data written to the filesystem without evident validation.",
        why_it_matters="Writing user-uploaded content or request fields to arbitrary paths can overwrite application files, enable webshell upload, or leak data.",
        recommendation="Validate file type, size, and name against an allowlist, store files in a dedicated directory with generated names, and never trust request-supplied paths.",
        ai_fix_prompt="Inspect the flagged upload and file-writing code. Determine where filenames and destinations come from and whether request data controls the path. Enforce type/size allowlists, generate safe filenames, and confine writes to a dedicated directory. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests for malicious filenames and unexpected file types. Verify the fix, then summarize the changes.",
        technical="Patterns like upload.save, createWriteStream, or req.files followed by a path use client-controlled names and locations. A crafted filename such as ../../shell.php can place content outside the upload directory.",
        beginner="When you let users upload files, never let their file names decide where files go on your server. Generate the name yourself and keep all uploads in one safe folder.",
        patterns=[
            r"(?i)(upload[^\n]{0,40}(save|writeFile|createWriteStream)|req\.files[^\n]{0,40}(path|save)|writeFile\s*\(\s*[^)]*(req\.|body\.|query\.))",
        ],
    ),
    Rule(
        rule_id="CODE-007",
        title="Open redirect",
        category="dangerous-code",
        severity=Severity.MEDIUM,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: redirect target derived from request input.",
        why_it_matters="If a redirect URL comes from user input, attackers can craft links that send victims to phishing sites while the domain looks trusted.",
        recommendation="Never redirect to raw request parameters. Only redirect to an allowlisted set of internal destinations, and validate the scheme and host.",
        ai_fix_prompt="Inspect the flagged redirect code. Identify which request parameters influence the destination. Restrict redirects to an allowlist of internal paths or validated absolute URLs, rejecting unknown targets. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests with external URL payloads to confirm they are not followed. Verify the fix, then summarize the changes.",
        technical="Passing request-provided URLs straight to redirect lets an attacker set Location to an external site. Legitimate redirect targets should be resolved from a small allowlist, never echoed from input.",
        beginner="A link that looks like it goes to your site can secretly send visitors to another site. Only redirect to destinations your own code chooses.",
        patterns=[
            r"(?i)(redirect\s*\(\s*(req\.query|req\.body|ctx\.query|request\.query)|res\.redirect\s*\(\s*[^)]*(query|param))",
        ],
    ),
    Rule(
        rule_id="CODE-008",
        title="Unsafe HTML injection (XSS)",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="Potential issue detected: user-controlled content injected into HTML without sanitization.",
        why_it_matters="Injecting unsanitized input into the DOM enables stored or reflected XSS, letting attackers run scripts in victims' browsers and steal sessions.",
        recommendation="Escape all dynamic content before inserting it into HTML. Prefer framework-provided safe bindings and sanitize any raw HTML before use.",
        ai_fix_prompt="Inspect the flagged innerHTML, dangerouslySetInnerHTML, v-html, .html(), and document.write call sites. Determine which values are user-controlled. Replace raw injection with escaped text or a sanitizer that strips script-bearing content. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests with XSS payloads to confirm scripts are neutralized. Verify the fix, then summarize the changes.",
        technical="Assigning user input to innerHTML or using dangerouslySetInnerHTML/v-html writes markup literally, so a payload like <img src=x onerror=alert(1)> executes. Safe rendering escapes or sanitizes the content first.",
        beginner="Web pages treat some text as instructions (HTML and scripts). If user text goes in as 'instructions', they can run their own code in other users' browsers. Always escape it as plain text.",
        patterns=[
            r"(?i)(\.innerHTML\s*=|dangerouslySetInnerHTML|v-html\s*=|\.html\s*\(\s*[$]|document\.write\s*\()",
        ],
    ),
    Rule(
        rule_id="CODE-009",
        title="Unsafe deserialization",
        category="dangerous-code",
        severity=Severity.HIGH,
        confidence=Confidence.LOW,
        description="Potential issue detected: deserialization of untrusted or weakly configured data.",
        why_it_matters="Unsafe deserializers such as pickle can execute arbitrary code, and unsafe YAML/JSON loading of untrusted sources can enable injection or data theft.",
        recommendation="Deserialize only trusted data. Use safe loaders (yaml.safe_load, pickle with signed data), and never deserialize request or localStorage input with unsafe APIs.",
        ai_fix_prompt="Inspect the flagged deserialization calls. Identify whether the input is untrusted and which loader is configured. Switch to safe loaders such as yaml.safe_load or JSON with explicit schema validation, and authenticate or sign any pickle data. Modify only the necessary files, avoid unrelated refactoring, and preserve existing functionality. Add or update tests covering malformed and malicious payloads. Verify the fix, then summarize the changes.",
        technical="pickle.loads can instantiate arbitrary objects and run code on load. yaml.load with a permissive Loader can similarly build arbitrary objects. Parsing untrusted request or localStorage data with these APIs is dangerous.",
        beginner="Some data formats are 'loadable' in a way that runs code when you read them. Never open data that came from a stranger with those tools. Use the safe reading methods instead.",
        patterns=[
            r"pickle\.loads\s*\(",
            r"yaml\.load\s*\(\s*[^)]*Loader\s*=\s*yaml\.(Full|Safe)?Loader?",
            r"JSON\.parse\s*\(\s*(localStorage|req\.|request\.|body)",
        ],
    ),
]
