from scanner.rules.base import Rule, Severity, Confidence

RULES: list[Rule] = [
    Rule(
        rule_id="SECRET-001",
        title="Hardcoded API credential",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="A hardcoded API key, secret, or token was found assigned in source code.",
        why_it_matters="Hardcoded credentials in source are the single most common way secrets leak. Anyone with read access to the repository can extract and reuse them, including on external services where they can incur cost, exfiltrate data, or trigger account compromise.",
        recommendation="Remove the credential immediately, rotate it if it may have been exposed, and load values from environment variables or a secrets manager instead.",
        ai_fix_prompt="Inspect the file that contains the hardcoded credential. Identify every place the literal secret appears, including tests, examples, and config. Replace the hardcoded value with a reference to an environment variable (for example os.environ.get in Python or process.env in Node). Keep the surrounding logic and behavior identical. Only modify the files that need the change. If tests assert on the literal secret value, update them to use the same environment-based lookup, and add or adjust tests to prove the code still works with a dummy value. Run the relevant test suite and verify nothing else broke. Summarize the changed files and the rotation step the developer must still perform.",
        technical="Pattern matches assignment forms such as `sk=...`, `api_key: ...`, or `secret=\"...\"` followed by a quoted value of at least 16 alphanumeric, underscore, or dash characters.",
        beginner="A secret is a password or key that unlocks a service. If it sits in the code file, anyone who sees the code can use it. Secrets should live in a hidden environment file or a vault, never in source.",
        patterns=[
            r"(?i)\b(sk|pk|api[_-]?key|apikey|secret|token)\s*[:=]\s*[\"']?[A-Za-z0-9_\-]{16,}[\"']?"
        ],
    ),
    Rule(
        rule_id="SECRET-002",
        title="Private key file committed to repository",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="A PEM or .key file containing a private key was found in the repository.",
        why_it_matters="A committed private key grants anyone with repo access the full cryptographic identity it represents — SSH access, TLS termination, or code signing. Once pushed, the key must be considered compromised because it may live forever in history and mirrors.",
        recommendation="Remove the key file from the repository and all history, rotate the key, and revoke it on every service that used it. Keep private keys out of version control and generate them on the host or in a secrets store.",
        ai_fix_prompt="Inspect the private key file. Do not print or copy the key material. Confirm whether the key is actually referenced by the project or was committed accidentally. If unused, delete the file from the working tree, update any import or config that references the path, and add the file name and pattern (for example *.key, *.pem) to .gitignore. If the key is in active use, do not delete it: instead note the exact files that reference it and recommend rotation, and update config to load the key from a secure location such as an environment variable path or secrets manager. Preserve functionality of anything that depends on the key. Run the test suite and verify nothing depends on the committed file. Summarize what changed and which manual rotation steps remain.",
        technical="Files_include matches paths containing .pem or .key. The pattern detects the PEM armor header that marks a private key block, including RSA, EC, and OpenSSH formats.",
        beginner="A private key is like the master key to your lock. If it is uploaded to the code folder and then to the internet, everyone can copy it and unlock what you protect.",
        patterns=[r"-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"],
        files_include=[".pem", ".key"],
    ),
    Rule(
        rule_id="SECRET-004",
        title="AI provider API key",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="An OpenAI or Anthropic API key was found in the codebase.",
        why_it_matters="AI provider keys bill usage directly to the owner's account. An exposed key can be used to spend money at scale or to query the account's models and history. Provider dashboards also show the key fingerprint, so it is identifiable at a glance.",
        recommendation="Delete and regenerate the key from the provider dashboard, then load it from an environment variable or secrets manager and never commit it.",
        ai_fix_prompt="Inspect the file that contains the AI provider key. Locate every occurrence of the key literal, including example files, docs, and tests. Replace it with an environment-variable lookup consistent with the project's language and existing config patterns. Keep all other code behavior identical and change only necessary files. Update or add tests that exercise the code path with a fake key to prove it still works. Run the tests and any linter, then confirm no occurrence of the original key remains in the working tree. Summarize the files changed and the provider-side rotation step.",
        technical="Pattern matches OpenAI-style keys (`sk-` followed by 20+ alphanumeric characters) and Anthropic-style keys (`sk-ant-` followed by 20+ alphanumeric, underscore, or dash characters).",
        beginner="An AI key lets you pay for AI usage. If it leaks in code, strangers can use your account and your money.",
        patterns=[r"\bsk-[A-Za-z0-9_\-]{20,}\b", r"\bsk-ant-[A-Za-z0-9_\-]{20,}\b"],
    ),
    Rule(
        rule_id="SECRET-005",
        title="Stripe live secret key",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="A Stripe live secret key was found in the codebase.",
        why_it_matters="A Stripe live secret key can charge cards, read customers, and move money without restriction. Exposure means direct financial damage plus regulatory liability under payment-card rules.",
        recommendation="Rotate the key immediately in the Stripe dashboard, verify no unauthorized charges occurred, and move the key to a secrets manager with access restricted to the server role only.",
        ai_fix_prompt="Inspect the file containing the Stripe key. Replace the literal with an environment-variable reference, matching how other config is loaded in the project. Never hardcode the replacement value anywhere else. Preserve the exact behavior of payment calls, and only edit necessary files. Add a test that the client initializes from the environment variable and works with a dummy key. Run tests and the linter, and verify no copy of the key remains in the tree or in tracked history concerns. Summarize changes and the mandatory Stripe dashboard rotation step.",
        technical="Pattern matches Stripe live secret keys of the form `sk_live_` followed by at least 16 alphanumeric characters. Test keys (`sk_test_`) are not matched because they are non-functional.",
        beginner="A Stripe key is the password to your payment account. If it leaks, someone can spend your customers' money.",
        patterns=[r"\bsk_live_[A-Za-z0-9]{16,}\b"],
    ),
    Rule(
        rule_id="SECRET-007",
        title="AWS access key ID",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="An AWS access key ID was found in the codebase.",
        why_it_matters="An AWS access key can read and write S3 buckets, start instances, and change IAM policies. Because the secret counterpart usually sits nearby in the same file or config, exposure frequently means full compromise of the account's permissions.",
        recommendation="Rotate the access key in IAM, remove the old key pair, audit CloudTrail for usage, and load credentials from IAM roles, the shared credentials file, or a vault instead of source.",
        ai_fix_prompt="Inspect the file containing the AWS access key ID. Replace the hardcoded credential with the project's existing configuration mechanism: environment variables, boto3 default credential chain, AWS profile files, or a secrets manager — matching what the code already does. Do not commit the replacement value. Change only files that reference the key and any tests that assert on it. Add a test that credentials resolve from the configured source rather than a literal. Run the test suite and linter, then confirm no key string remains in the tree. Summarize changes and the IAM rotation step that must be performed manually.",
        technical="Pattern matches the 20-character AKIA-prefixed access key ID format. The companion secret access key usually appears on an adjacent line.",
        beginner="An AWS key is the ID card for your cloud account. Someone with it can read your files and spend your cloud budget.",
        patterns=[r"\bAKIA[0-9A-Z]{16}\b"],
    ),
    Rule(
        rule_id="SECRET-008",
        title="Hardcoded bearer or access token",
        category="secrets",
        severity=Severity.HIGH,
        confidence=Confidence.MEDIUM,
        description="A bearer token, access token, or auth token literal was found assigned in the code.",
        why_it_matters="Tokens are short-lived but valuable: exposed ones authenticate API calls as a real user or service and can be replayed until they expire. Medium confidence reflects that the matched string may be a placeholder rather than a live token.",
        recommendation="Move the token to an environment variable or vault, and check token-revocation endpoints to invalidate any that were genuinely exposed.",
        ai_fix_prompt="Inspect the file containing the token assignment. Determine whether the value is a real token or a placeholder. Replace real tokens with an environment-variable or config lookup, keeping the code path identical. Leave placeholder-looking values alone or mark them clearly as dummies only if they are used in tests. Modify only necessary files. Add or update tests that verify the token is read from the configured source. Run tests and the linter, and verify the real value no longer appears in the tree. Summarize the changes and any manual token revocation needed.",
        technical="Pattern matches `Bearer`, `access_token`, or `auth_token` followed by an assignment and a quoted value of at least 20 characters. Evidence is the matched literal only.",
        beginner="A token is a short-lived password for an API. If it is in the code file, someone who sees the file can call the API as you until the token expires.",
        patterns=[
            r"(?i)\b(Bearer|access_token|auth_token)\s*[:=]\s*[\"'][A-Za-z0-9_\-\.]{20,}[\"']"
        ],
    ),
    Rule(
        rule_id="SECRET-006",
        title="Database connection string with credentials",
        category="secrets",
        severity=Severity.CRITICAL,
        confidence=Confidence.HIGH,
        description="A database connection string containing a username and password was found in the code.",
        why_it_matters="A connection string with embedded credentials grants full database access. Exposing it leaks all stored data, including PII, and enables deletion or ransomware-style damage.",
        recommendation="Remove the credentials from the string, store them in a secrets manager or environment variables, and rotate the database password if the string was ever pushed.",
        ai_fix_prompt="Inspect the file containing the connection string. Remove the embedded password, keeping the host, port, and database parts. Rebuild the string from environment variables at runtime using the project's existing configuration helpers. Ensure code that connects uses the constructed value, preserving all behavior. Update tests to feed a dummy user and password via environment variables and verify connectivity code paths still construct correctly. Run the test suite and linter. Confirm no `user:password@` pattern remains in the tree. Summarize changed files and the required database password rotation step.",
        technical="Pattern matches postgres, postgresql, mysql, or mongodb connection URIs that contain a `user:password@` segment before the host.",
        beginner="A database link with a password inside is like writing the safe combination on the safe door. Anyone reading the code gets into all your data.",
        patterns=[
            r"(?i)\b(postgres|postgresql|mysql|mongodb(\+srv)?)://[^\s/]+:[^\s@]+@"
        ],
    ),
    Rule(
        rule_id="SECRET-009",
        title="Secret embedded in frontend or bundled JavaScript",
        category="secrets",
        severity=Severity.HIGH,
        confidence=Confidence.HIGH,
        description="A service key that should stay server-side was found assigned in frontend or bundled JavaScript.",
        why_it_matters="Anything shipped to the browser is visible to every visitor. Keys like the Supabase service_role key or a Firebase API key bundled in JS are extractable in seconds and grant elevated access to the backend.",
        recommendation="Restrict such keys with allow-lists on the backend provider, move privileged service keys to the server, and use the least-privilege public (anon) key for the client.",
        ai_fix_prompt="Inspect the frontend or bundle file that assigns the service key. Determine what privilege the key carries. If it is a privileged server-only key, remove it from the client code and have the client call a server endpoint that performs the operation with the privileged key. If it is a public anon key that the provider allows in browsers, keep it but confirm provider allow-lists are configured. Keep app behavior intact and modify only the necessary files. Add or update tests covering the client-server flow. Run the frontend build and tests, and verify no privileged key appears in bundled output. Summarize the changes and the provider-side restriction that must be configured.",
        technical="Pattern matches assignments of Supabase `supabaseKey`/`service_role`, Firebase `firebaseApiKey`, and generic `serviceRole` variables, which are frequently shipped in client bundles.",
        beginner="Code that runs in your browser is visible to every visitor. Putting a master key there is like posting your front-door key on the door.",
        patterns=[
            r"(?i)\b(supabaseKey|firebaseApiKey|service_role|serviceRole)\s*[:=]"
        ],
    ),
]
